### ISSUE TITLE
Leading zero removed is this a bug

### ISSUE THREAD

**Issue by developer9969** [marcusoftnet/SpecFlow.Assist.Dynamic#14]
Hi
just came accross your extension and it's brilliant I removed at least 50 classes.
However i have encountered some issues with leading zero .
When presented with something like
| myfield          |07|
| myfield2	|01| 
and I need the zero to be there it gets removed!
also if you have a date like this 
|mydate        |12/2017| and you want it to be a string it converts to a full date and then i have to reformat it.

Is there a way to make prevent to remove the zero?
In my specflow tests I treat everything as a string because eventually selenium wants always a string eg Sendkeys,

Suggestions

**Comment by marcusoftnet** [comment]
Ah - good catch... It has to do with the way I'm converting it into values for the dynamic.

I have no quick way of testing this but now, but maybe you could surround it with quotes to ... force it to be treated as string, as a workaround

**Comment by developer9969** [comment]
thanks for your quick reply do you mean in specflow like this | myfield2	|"01"|  not sure what you mean.
thanks

**Comment by marcusoftnet** [comment]
@developer9969, yes the quotes as you wrote it is a suggestion for a workaround to see if you can force it to be a string. Or if you can prefix it with a letter - just to "trick" my library into treating it as a string. 

Here's a description of the [convention based type convention](https://github.com/marcusoftnet/SpecFlow.Assist.Dynamic/wiki/Conversion-conventions) I'm using, to assist you in your tricking of my library. 

Sadly there is no way to force it to be a string - and since I've used a convention based conversion function from the outset we probably have to add a configuration property to be able to change that. 

Something like 
```xml
  <specFlow.Assist.Dyamic>
		<useConventionBaseTypeConversion>false</useConventionBaseTypeConversion>
  </specFlow.Assist.Dyamic>
```

That means that if you set this value to false we will always just use strings. Otherwise, the default behaviour is to do the convention base type conversion as today. 

@darrencauthon - what do you think? Would that be a good approach? 

Sadly my Windows-time these day is ... seldom. Don't even have a virtual windows around anymore. If we like this approach I'll get around of making this happen.

**Comment by marcusoftnet** [comment]
@developer9969 now read my comment from late yesterday I see that it needs some more input. 

As a workaround i mean that you can do `_07` instead of `07`

**Comment by marcusoftnet** [comment]
I've fixed this for you @developer9969 

Read the documentation at https://github.com/marcusoftnet/SpecFlow.Assist.Dynamic/wiki/Conversion-conventions#disabling-type-conversion and get an updated version of SpecFlow.Assist.Dynamic from NuGet. 1.3.0 contains this fix. 

Please let me know how it's working for you

**Comment by developer9969** [comment]
Thanks for fixing this so promptly. It does work with your sample but not with mine  try this 
                | Field					|Value|
		| myfield1				|02|
		| myfield2				|01|

and see what you get ? Am I missing the obvious here
thanks again

**Comment by marcusoftnet** [comment]
Hmmm - sitting on a Mac again and I have no easy way to test this right now, but from the formatting above I'm thinking that maybe the `|` needs spaces on the side? 

If my examples work, how about modifying them little by little and see if you can understand what is different?

**Comment by marcusoftnet** [comment]
@developer9969 that is a bug! A missing case that I didn't account for. 

Uploading 1.3.1 version of this tool to nuget as we speak. 

The gist of it is that you can create an instance from a table with one row of header and values - like this: 
```cucumber
Scenario: There's ways to disable type conversion for instance creation
	When I create a dynamic instance from this table using no type conversion
		| Name   | Age | Birth date | Length in meters |
		| 012345 | 044 | 1972-13-09 | 1,96             | 
	Then the Name value should still be '012345'
	And the Age value should still be '044'
	And the birth date should stil be '1972-13-09'
	And length in meter should still be '1,96'
```
But your case is a special case, when there are two columns. Because that is [interpreted by SpecFlow.Assist.Dynamic](https://github.com/marcusoftnet/SpecFlow.Assist.Dynamic/wiki/Table-to-dynamic-instance) as a key/value table that will used like this: 

```cucumber
Scenario: There's ways to disable type conversion for instance creation with key/value tables
	When I create a dynamic instance from this table using no type conversion
		| Key              | Value | 
		| Name             | 012345 | 
		| Age              | 044 | 
		| Birth date       | 1972-13-09 | 
		| Length in meters | 1,96 | 
	Then the Name value should still be '012345'
	And the Age value should still be '044'
	And the birth date should stil be '1972-13-09'
	And length in meter should still be '1,96'
```

But I didn't handle the second case (key/value pairs) until now. Thanks for pointing that out. 

SpecFlow.Assist.Dynamic 1.3.1 should fix this for you.

Thank you for making my little tool better!

**Comment by developer9969** [comment]
Hi debugged the code and for some reason  it always hits the 1st "if" statement  cannot work out why it thinks more than 1 rowcount is the way i layout the data in the feature?
![image](https://cloud.githubusercontent.com/assets/16970109/23059707/81b5fb48-f4f2-11e6-93e6-1590214acdb2.png)

![image](https://cloud.githubusercontent.com/assets/16970109/23059784/cb89a210-f4f2-11e6-98d8-e0df05478fc5.png)

anyway I will play with it at the weekend .

**Comment by developer9969** [comment]
thanks to you your tool is GREAT!

**Comment by marcusoftnet** [comment]
Happy to hear that @developer9969 - does that mean that it works, reg your debugging above?
