### ISSUE TITLE
Support .NET Core, .NET Standard #20

### ISSUE THREAD

**Issue by astastast** [marcusoftnet/SpecFlow.Assist.Dynamic#22]
Please support new frameworks .NET Core, .NET Standard

**Comment by marcusoftnet** [comment]
Should be fixed now - as per https://www.nuget.org/packages/SpecFlow.Assist.Dynamic/1.4.0-beta

Please test and report bugs if you find any. 

THANK you for your patience with this. I don't have access to a Windows Environment and had to learn how to build this on my Mac. Learnt a lot but it took time.

**Comment by LiohAu** [comment]
Hello, 
I am having  a build error when I restore nuget packages in a TFS build on a windows build agent whereas it works locally on another windows and on my OSX : 

hecking compatibility for SpecFlow.Assist.Dynamic 1.4.1 with .NETFramework,Version=v4.6.1.
Package SpecFlow.Assist.Dynamic 1.4.1 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package SpecFlow.Assist.Dynamic 1.4.1 supports:
  - 452 (452,Version=v0.0)
  - 462 (462,Version=v0.0)
  - 472 (472,Version=v0.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by marcusoftnet** [comment]
Yes it is and it's, as I read it, due to the fact that you are using 4.6.1 and my package doesn't support that. I think I've solved it but have a really hard time testing this, as I don't have a Windows machine

But I created a unlisted version and I hope that you can use that and verify that it works

https://www.nuget.org/packages/SpecFlow.Assist.Dynamic/1.4.2-beta

**Comment by marcusoftnet** [comment]
I've updated the package now so it supports 461 too 

https://www.nuget.org/packages/SpecFlow.Assist.Dynamic/1.4.2
